export const AD_LIST_REQUEST = 'AD_LIST_REQUEST';
export const AD_LIST_SUCCESS = 'AD_LIST_SUCCESS';
export const AD_LIST_FAIL = 'AD_LIST_FAIL';
export const AD_DETAILS_REQUEST = 'AD_DETAILS_REQUEST';
export const AD_DETAILS_SUCCESS = 'AD_DETAILS_SUCCESS';
export const AD_DETAILS_FAIL = 'AD_DETAILS_FAIL'