export const AUTO_SAVE_REQUEST = 'AUTO_SAVE_REQUEST';
export const AUTO_SAVE_SUCCESS = 'AUTO_SAVE_SUCCESS';
export const AUTO_SAVE_FAIL = 'AUTO_SAVE_FAIL';

export const AUTO_LIST_REQUEST = 'AUTO_LIST_REQUEST';
export const AUTO_LIST_SUCCESS = 'AUTO_LIST_SUCCESS';
export const AUTO_LIST_FAIL = 'AUTO_LIST_FAIL';

export const AUTO_DETAILS_REQUEST = 'AUTO_DETAILS_REQUEST';
export const AUTO_DETAILS_SUCCESS = 'AUTO_DETAILS_SUCCESS';
export const AUTO_DETAILS_FAIL = 'AUTO_DETAILS_FAIL';

export const AUTO_DELETE_REQUEST = 'AUTO_DELETE_REQUEST';
export const AUTO_DELETE_SUCCESS = 'AUTO_DELETE_SUCCESS';
export const AUTO_DELETE_FAIL = 'AUTO_DELETE_FAIL';
