export default {
  ads: [
    {
      _id: '1',
      image: "/images/d1.jpg",
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      price: "1000000 so'm",
    },
    {
      _id: '2',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
    {
      _id: '3',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
    {
      _id: '4',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
    {
      _id: '5',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
    {
      _id: '6',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
    {
      _id: '7',
      image: "/images/d1.jpg",
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      price: "1000000 so'm",
    },
    {
      _id: '8',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
    {
      _id: '9',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
    {
      _id: '10',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
    {
      _id: '11',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
    {
      _id: '12',
      name: "1 Xonalik Novostroyka",
      title: "1 Xonalik Novostroyka",
      description: "1 Xonalik Novostroykalar Tel:+998909900290",
      sort: "1-Xonalik",
      image: "/images/d1.jpg",
      price: "1000000 so'm",
    },
  ],
};
